"""
Unit tests for app.services.claim_service — Task 5.

Uses in-memory fake repositories instead of moto/mocked AWS, so no
AWS credentials or real DynamoDB calls are required.

Covers:
  create_claim:
  - valid claim created and persisted
  - invalid policy number raises ValidationError
  - missing incidentDateTime raises ValidationError
  - missing incidentLocation raises ValidationError
  - claimantId comes from auth context, never from body
  - claimId is generated by the service/domain (not supplied)
  - initial status is always CREATED
  - repository save() called exactly once
  - description is optional

  get_claim_with_evidence:
  - claim returned with evidence list
  - claim not found raises NotFoundError (CLAIM_NOT_FOUND)
  - wrong claimant raises ForbiddenError
  - evidence list is populated from repo
  - empty evidence list returned when no evidence exists
  - response does not expose claimantId
"""

from __future__ import annotations

from typing import Any

import pytest

from app.domain.exceptions import ForbiddenError, NotFoundError, ValidationError
from app.services.claim_service import ClaimService

# ── Shared test constants ─────────────────────────────────────────────────────

CLAIMANT_ID = "cognito-sub-aaa-111"
OTHER_CLAIMANT_ID = "cognito-sub-bbb-222"
CLAIM_ID = "CLM-550e8400-e29b-41d4-a716-446655440000"
FIXED_TIME = "2026-09-30T10:00:00+00:00"

VALID_BODY: dict[str, Any] = {
    "policyNumber": "POL-123456",
    "incidentDateTime": "2026-09-15T14:30:00Z",
    "incidentLocation": "123 Main St, Springfield",
    "description": "Rear-ended at traffic lights.",
}


# ── In-memory fake repositories ───────────────────────────────────────────────


class FakeClaimRepository:
    """In-memory ClaimRepository replacement for unit tests."""

    def __init__(self) -> None:
        self._store: dict[str, dict[str, Any]] = {}
        self.save_call_count = 0

    def save(self, item: dict[str, Any]) -> None:
        self._store[item["claimId"]] = item
        self.save_call_count += 1

    def get(self, claim_id: str) -> dict[str, Any] | None:
        return self._store.get(claim_id)

    def update_status_conditional(
        self,
        claim_id: str,
        expected_current_status: str,
        new_status: str,
        updated_at: str,
    ) -> bool:
        item = self._store.get(claim_id)
        if item is None or item.get("status") != expected_current_status:
            return False
        item["status"] = new_status
        item["updatedAt"] = updated_at
        return True

    def seed(self, item: dict[str, Any]) -> None:
        """Directly insert a claim item for test setup."""
        self._store[item["claimId"]] = item


class FakeEvidenceRepository:
    """In-memory EvidenceRepository replacement for unit tests."""

    def __init__(self) -> None:
        self._store: dict[str, dict[str, Any]] = {}

    def save(self, item: dict[str, Any]) -> None:
        self._store[item["evidenceId"]] = item

    def get(self, evidence_id: str) -> dict[str, Any] | None:
        return self._store.get(evidence_id)

    def list_by_claim(self, claim_id: str) -> list[dict[str, Any]]:
        return [v for v in self._store.values() if v.get("claimId") == claim_id]

    def count_completed_by_claim(self, claim_id: str) -> int:
        return sum(
            1
            for v in self._store.values()
            if v.get("claimId") == claim_id and v.get("status") == "UPLOAD_COMPLETE"
        )

    def update_status_conditional(
        self,
        evidence_id: str,
        expected_current_status: str,
        new_status: str,
        updated_at: str,
        uploaded_at: str | None = None,
    ) -> bool:
        item = self._store.get(evidence_id)
        if item is None or item.get("status") != expected_current_status:
            return False
        item["status"] = new_status
        item["updatedAt"] = updated_at
        if uploaded_at is not None:
            item["uploadedAt"] = uploaded_at
        return True

    def seed(self, item: dict[str, Any]) -> None:
        self._store[item["evidenceId"]] = item


# ── Helpers ───────────────────────────────────────────────────────────────────


def _make_service(
    claim_repo: FakeClaimRepository | None = None,
    evidence_repo: FakeEvidenceRepository | None = None,
) -> tuple[ClaimService, FakeClaimRepository, FakeEvidenceRepository]:
    cr = claim_repo or FakeClaimRepository()
    er = evidence_repo or FakeEvidenceRepository()
    svc = ClaimService(cr, er, clock=lambda: FIXED_TIME)  # type: ignore[arg-type]
    return svc, cr, er


def _make_claim_item(
    claim_id: str = CLAIM_ID,
    claimant_id: str = CLAIMANT_ID,
    status: str = "CREATED",
) -> dict[str, Any]:
    return {
        "claimId": claim_id,
        "claimantId": claimant_id,
        "policyNumber": "POL-123456",
        "incidentDateTime": "2026-09-15T14:30:00Z",
        "incidentLocation": "123 Main St, Springfield",
        "description": "Rear-ended.",
        "status": status,
        "createdAt": FIXED_TIME,
        "updatedAt": FIXED_TIME,
    }


def _make_evidence_item(
    evidence_id: str = "EVD-aaa-111",
    claim_id: str = CLAIM_ID,
    status: str = "UPLOAD_PENDING",
) -> dict[str, Any]:
    return {
        "evidenceId": evidence_id,
        "claimId": claim_id,
        "claimantId": CLAIMANT_ID,
        "evidenceType": "VIDEO",
        "originalFileName": "accident.mp4",
        "contentType": "video/mp4",
        "fileSizeBytes": 1024,
        "storageKey": f"claims/{claim_id}/evidence/{evidence_id}/object",
        "status": status,
        "createdAt": FIXED_TIME,
    }


# ── create_claim ──────────────────────────────────────────────────────────────


class TestCreateClaim:
    def test_valid_claim_returns_response(self) -> None:
        """Happy path — valid input produces a ClaimResponse."""
        svc, cr, _ = _make_service()
        result = svc.create_claim(CLAIMANT_ID, VALID_BODY)
        assert result["claimId"].startswith("CLM-")
        assert result["status"] == "CREATED"
        assert result["policyNumber"] == "POL-123456"

    def test_claim_persisted_in_repository(self) -> None:
        """The created claim is saved to the repository."""
        svc, cr, _ = _make_service()
        result = svc.create_claim(CLAIMANT_ID, VALID_BODY)
        saved = cr.get(result["claimId"])
        assert saved is not None
        assert saved["claimId"] == result["claimId"]

    def test_repository_save_called_exactly_once(self) -> None:
        """save() is called exactly once per create_claim call."""
        svc, cr, _ = _make_service()
        svc.create_claim(CLAIMANT_ID, VALID_BODY)
        assert cr.save_call_count == 1

    def test_initial_status_is_created(self) -> None:
        """Newly created claim always has status CREATED."""
        svc, _, _ = _make_service()
        result = svc.create_claim(CLAIMANT_ID, VALID_BODY)
        assert result["status"] == "CREATED"

    def test_claimant_id_from_auth_context_not_body(self) -> None:
        """claimantId is sourced from the auth parameter, not the body."""
        svc, cr, _ = _make_service()
        body_with_injected_id = {**VALID_BODY, "claimantId": "injected-id"}
        result = svc.create_claim(CLAIMANT_ID, body_with_injected_id)
        saved = cr.get(result["claimId"])
        assert saved is not None
        assert saved["claimantId"] == CLAIMANT_ID
        assert saved["claimantId"] != "injected-id"

    def test_claim_id_not_accepted_from_body(self) -> None:
        """claimId in the body is ignored; service generates its own."""
        svc, _, _ = _make_service()
        body_with_id = {**VALID_BODY, "claimId": "CLM-client-supplied"}
        result = svc.create_claim(CLAIMANT_ID, body_with_id)
        assert result["claimId"] != "CLM-client-supplied"
        assert result["claimId"].startswith("CLM-")

    def test_timestamps_are_set(self) -> None:
        """createdAt and updatedAt are populated from the clock."""
        svc, _, _ = _make_service()
        result = svc.create_claim(CLAIMANT_ID, VALID_BODY)
        assert result["createdAt"] == FIXED_TIME
        assert result["updatedAt"] == FIXED_TIME

    def test_description_is_optional(self) -> None:
        """Claim creation succeeds when description is absent from body."""
        svc, _, _ = _make_service()
        body = {k: v for k, v in VALID_BODY.items() if k != "description"}
        result = svc.create_claim(CLAIMANT_ID, body)
        assert result["claimId"].startswith("CLM-")
        assert "description" not in result

    def test_description_included_when_provided(self) -> None:
        """description is included in the response when present."""
        svc, _, _ = _make_service()
        result = svc.create_claim(CLAIMANT_ID, VALID_BODY)
        assert result["description"] == "Rear-ended at traffic lights."

    def test_invalid_policy_number_raises_validation_error(self) -> None:
        """Blank policyNumber raises ValidationError."""
        svc, _, _ = _make_service()
        with pytest.raises(ValidationError) as exc_info:
            svc.create_claim(CLAIMANT_ID, {**VALID_BODY, "policyNumber": "  "})
        assert "policyNumber" in exc_info.value.message

    def test_missing_policy_number_raises_validation_error(self) -> None:
        """Missing policyNumber raises ValidationError."""
        svc, _, _ = _make_service()
        body = {k: v for k, v in VALID_BODY.items() if k != "policyNumber"}
        with pytest.raises(ValidationError) as exc_info:
            svc.create_claim(CLAIMANT_ID, body)
        assert "policyNumber" in exc_info.value.message

    def test_missing_incident_datetime_raises_validation_error(self) -> None:
        """Missing incidentDateTime raises ValidationError."""
        svc, _, _ = _make_service()
        body = {k: v for k, v in VALID_BODY.items() if k != "incidentDateTime"}
        with pytest.raises(ValidationError) as exc_info:
            svc.create_claim(CLAIMANT_ID, body)
        assert "incidentDateTime" in exc_info.value.message

    def test_missing_incident_location_raises_validation_error(self) -> None:
        """Missing incidentLocation raises ValidationError."""
        svc, _, _ = _make_service()
        body = {k: v for k, v in VALID_BODY.items() if k != "incidentLocation"}
        with pytest.raises(ValidationError) as exc_info:
            svc.create_claim(CLAIMANT_ID, body)
        assert "incidentLocation" in exc_info.value.message

    def test_response_does_not_expose_claimant_id(self) -> None:
        """claimantId must not appear in the public claim response."""
        svc, _, _ = _make_service()
        result = svc.create_claim(CLAIMANT_ID, VALID_BODY)
        assert "claimantId" not in result

    def test_two_creates_produce_different_claim_ids(self) -> None:
        """Each call generates a unique claimId."""
        svc, _, _ = _make_service()
        r1 = svc.create_claim(CLAIMANT_ID, VALID_BODY)
        r2 = svc.create_claim(CLAIMANT_ID, VALID_BODY)
        assert r1["claimId"] != r2["claimId"]


# ── get_claim_with_evidence ───────────────────────────────────────────────────


class TestGetClaimWithEvidence:
    def test_returns_claim_and_evidence_list(self) -> None:
        """Claim with associated evidence is returned correctly."""
        svc, cr, er = _make_service()
        cr.seed(_make_claim_item())
        er.seed(_make_evidence_item("EVD-111"))
        er.seed(_make_evidence_item("EVD-222"))

        result = svc.get_claim_with_evidence(CLAIM_ID, CLAIMANT_ID)
        assert result["claimId"] == CLAIM_ID
        assert len(result["evidence"]) == 2

    def test_returns_empty_evidence_list_when_none_exist(self) -> None:
        """Evidence list is empty when no evidence records exist."""
        svc, cr, _ = _make_service()
        cr.seed(_make_claim_item())

        result = svc.get_claim_with_evidence(CLAIM_ID, CLAIMANT_ID)
        assert result["evidence"] == []

    def test_claim_not_found_raises_not_found_error(self) -> None:
        """Non-existent claimId raises NotFoundError with CLAIM_NOT_FOUND."""
        svc, _, _ = _make_service()
        with pytest.raises(NotFoundError) as exc_info:
            svc.get_claim_with_evidence("CLM-does-not-exist", CLAIMANT_ID)
        assert exc_info.value.error_code == "CLAIM_NOT_FOUND"

    def test_wrong_claimant_raises_forbidden_error(self) -> None:
        """Accessing another claimant's claim raises ForbiddenError."""
        svc, cr, _ = _make_service()
        cr.seed(_make_claim_item(claimant_id=OTHER_CLAIMANT_ID))

        with pytest.raises(ForbiddenError):
            svc.get_claim_with_evidence(CLAIM_ID, CLAIMANT_ID)

    def test_evidence_only_for_this_claim_returned(self) -> None:
        """Evidence from other claims is not included in the response."""
        svc, cr, er = _make_service()
        cr.seed(_make_claim_item())
        er.seed(_make_evidence_item("EVD-mine", claim_id=CLAIM_ID))
        er.seed(_make_evidence_item("EVD-other", claim_id="CLM-other"))

        result = svc.get_claim_with_evidence(CLAIM_ID, CLAIMANT_ID)
        ids = {e["evidenceId"] for e in result["evidence"]}
        assert ids == {"EVD-mine"}

    def test_response_does_not_expose_claimant_id(self) -> None:
        """claimantId must not appear in the claim response."""
        svc, cr, _ = _make_service()
        cr.seed(_make_claim_item())
        result = svc.get_claim_with_evidence(CLAIM_ID, CLAIMANT_ID)
        assert "claimantId" not in result

    def test_evidence_response_contains_required_fields(self) -> None:
        """Each evidence item in the response has the required fields."""
        svc, cr, er = _make_service()
        cr.seed(_make_claim_item())
        er.seed(_make_evidence_item("EVD-001"))
        result = svc.get_claim_with_evidence(CLAIM_ID, CLAIMANT_ID)
        ev = result["evidence"][0]
        for key in ("evidenceId", "claimId", "evidenceType", "status", "createdAt"):
            assert key in ev, f"Missing evidence key: {key}"

    def test_claim_response_contains_required_fields(self) -> None:
        """Claim response contains all required top-level fields."""
        svc, cr, _ = _make_service()
        cr.seed(_make_claim_item())
        result = svc.get_claim_with_evidence(CLAIM_ID, CLAIMANT_ID)
        for key in (
            "claimId",
            "policyNumber",
            "incidentDateTime",
            "incidentLocation",
            "status",
            "createdAt",
            "updatedAt",
            "evidence",
        ):
            assert key in result, f"Missing claim key: {key}"

    def test_get_owned_claim_helper_not_found(self) -> None:
        """_get_owned_claim raises CLAIM_NOT_FOUND for missing claim."""
        svc, _, _ = _make_service()
        with pytest.raises(NotFoundError) as exc_info:
            svc._get_owned_claim("CLM-missing", CLAIMANT_ID)
        assert exc_info.value.error_code == "CLAIM_NOT_FOUND"

    def test_get_owned_claim_helper_wrong_owner(self) -> None:
        """_get_owned_claim raises ForbiddenError for wrong claimant."""
        svc, cr, _ = _make_service()
        cr.seed(_make_claim_item(claimant_id=OTHER_CLAIMANT_ID))
        with pytest.raises(ForbiddenError):
            svc._get_owned_claim(CLAIM_ID, CLAIMANT_ID)

    def test_try_transition_updates_claim_when_eligible(self) -> None:
        """_try_transition_claim_to_evidence_submitted transitions when count >= 1."""
        svc, cr, er = _make_service()
        cr.seed(_make_claim_item(status="CREATED"))
        er.seed(_make_evidence_item(status="UPLOAD_COMPLETE"))

        svc._try_transition_claim_to_evidence_submitted(CLAIM_ID, "CREATED")

        item = cr.get(CLAIM_ID)
        assert item is not None
        assert item["status"] == "EVIDENCE_SUBMITTED"

    def test_try_transition_no_op_when_no_completed_evidence(self) -> None:
        """_try_transition does nothing when no evidence is complete."""
        svc, cr, er = _make_service()
        cr.seed(_make_claim_item(status="CREATED"))
        er.seed(_make_evidence_item(status="UPLOAD_PENDING"))

        svc._try_transition_claim_to_evidence_submitted(CLAIM_ID, "CREATED")

        item = cr.get(CLAIM_ID)
        assert item is not None
        assert item["status"] == "CREATED"

    def test_try_transition_no_op_when_already_transitioned(self) -> None:
        """_try_transition is a no-op when claim is already EVIDENCE_SUBMITTED."""
        svc, cr, er = _make_service()
        cr.seed(_make_claim_item(status="EVIDENCE_SUBMITTED"))
        er.seed(_make_evidence_item(status="UPLOAD_COMPLETE"))

        svc._try_transition_claim_to_evidence_submitted(CLAIM_ID, "EVIDENCE_SUBMITTED")

        item = cr.get(CLAIM_ID)
        assert item is not None
        assert item["status"] == "EVIDENCE_SUBMITTED"
