"""
Unit tests for app.services.evidence_service — Task 5.

Uses in-memory fake repositories (from test_service_claims) and a fake
S3Repository.  No AWS credentials or real AWS calls required.

Covers:
  request_upload_url:
  - valid VIDEO / AUDIO / POLICY_DOCUMENT
  - invalid MIME type raises ValidationError (UNSUPPORTED_CONTENT_TYPE)
  - file size over limit raises ValidationError (FILE_SIZE_EXCEEDED)
  - claim not found raises NotFoundError
  - unauthorized claimant raises ForbiddenError
  - evidence saved as UPLOAD_PENDING
  - storageKey generated by backend (no filename)
  - original filename not included in storageKey
  - presignedUrl returned and used correct storage key
  - multiple evidence records for same type are supported
  - response contains required fields

  confirm_upload:
  - successful confirmation → UPLOAD_COMPLETE
  - S3 object missing → ValidationError
  - evidence already UPLOAD_COMPLETE → idempotent (returns existing)
  - repeated confirmation is safe
  - claim ownership failure → ForbiddenError
  - evidence ownership failure → ForbiddenError
  - evidence belongs to different claim → NotFoundError/ForbiddenError
  - evidence transition is persisted
  - claim transitions to EVIDENCE_SUBMITTED
  - concurrent confirmation behavior (conditional update returns False)
  - no AI processing invoked
"""

from __future__ import annotations

from typing import Any
from unittest.mock import MagicMock

import pytest

from app.domain.exceptions import ForbiddenError, NotFoundError, ValidationError
from app.services.evidence_service import EvidenceService

# Re-use the in-memory fakes from the claims test module
from tests.unit.test_service_claims import (
    CLAIM_ID,
    CLAIMANT_ID,
    FIXED_TIME,
    OTHER_CLAIMANT_ID,
    FakeClaimRepository,
    FakeEvidenceRepository,
    _make_claim_item,
    _make_evidence_item,
)

# ── Shared constants ──────────────────────────────────────────────────────────

EVIDENCE_ID = "EVD-7f3c9a12-4b2e-4a8f-9c1d-2e3f4a5b6c7d"

DEFAULT_SIZE_LIMITS: dict[str, int] = {
    "VIDEO": 524288000,
    "AUDIO": 52428800,
    "POLICY_DOCUMENT": 10485760,
}

VALID_VIDEO_BODY: dict[str, Any] = {
    "evidenceType": "VIDEO",
    "fileName": "accident.mp4",
    "contentType": "video/mp4",
    "fileSizeBytes": 10_000_000,
}

VALID_AUDIO_BODY: dict[str, Any] = {
    "evidenceType": "AUDIO",
    "fileName": "description.mp3",
    "contentType": "audio/mpeg",
    "fileSizeBytes": 2_000_000,
}

VALID_PDF_BODY: dict[str, Any] = {
    "evidenceType": "POLICY_DOCUMENT",
    "fileName": "policy.pdf",
    "contentType": "application/pdf",
    "fileSizeBytes": 500_000,
}


# ── Fake S3 repository ────────────────────────────────────────────────────────


class FakeS3Repository:
    """In-memory S3Repository replacement for unit tests."""

    def __init__(self, object_exists_default: bool = True) -> None:
        self._existing_keys: set[str] = set()
        self._object_exists_default = object_exists_default
        self.presigned_url_calls: list[dict[str, Any]] = []

    def generate_presigned_put_url(
        self,
        key: str,
        content_type: str,
        expiry_seconds: int,
    ) -> str:
        self.presigned_url_calls.append(
            {"key": key, "content_type": content_type, "expiry_seconds": expiry_seconds}
        )
        return f"https://s3.example.com/{key}?presigned=true"

    def object_exists(self, key: str) -> bool:
        if key in self._existing_keys:
            return True
        return self._object_exists_default

    def add_object(self, key: str) -> None:
        self._existing_keys.add(key)

    def remove_object(self, key: str) -> None:
        self._existing_keys.discard(key)


# ── Factory helpers ───────────────────────────────────────────────────────────


def _make_evidence_service(
    claim_repo: FakeClaimRepository | None = None,
    evidence_repo: FakeEvidenceRepository | None = None,
    s3_repo: FakeS3Repository | None = None,
    size_limits: dict[str, int] | None = None,
    object_exists: bool = True,
) -> tuple[EvidenceService, FakeClaimRepository, FakeEvidenceRepository, FakeS3Repository]:
    cr = claim_repo or FakeClaimRepository()
    er = evidence_repo or FakeEvidenceRepository()
    s3 = s3_repo or FakeS3Repository(object_exists_default=object_exists)
    svc = EvidenceService(
        claim_repo=cr,
        evidence_repo=er,
        s3_repo=s3,  # type: ignore[arg-type]
        size_limits=size_limits or DEFAULT_SIZE_LIMITS,
        presigned_url_expiry_seconds=900,
        clock=lambda: FIXED_TIME,
    )
    return svc, cr, er, s3


# ── request_upload_url ────────────────────────────────────────────────────────


class TestRequestUploadUrl:
    def test_valid_video_evidence(self) -> None:
        """Valid VIDEO request returns expected response fields."""
        svc, cr, er, s3 = _make_evidence_service()
        cr.seed(_make_claim_item())

        result = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, VALID_VIDEO_BODY)

        assert result["evidenceId"].startswith("EVD-")
        assert result["claimId"] == CLAIM_ID
        assert result["status"] == "UPLOAD_PENDING"
        assert result["evidenceType"] == "VIDEO"
        assert result["contentType"] == "video/mp4"
        assert "presignedUrl" in result
        assert "storageKey" in result
        assert "urlExpiresAt" in result

    def test_valid_audio_evidence(self) -> None:
        """Valid AUDIO request returns expected response fields."""
        svc, cr, _, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        result = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, VALID_AUDIO_BODY)

        assert result["evidenceType"] == "AUDIO"
        assert result["contentType"] == "audio/mpeg"
        assert result["status"] == "UPLOAD_PENDING"

    def test_valid_policy_document_evidence(self) -> None:
        """Valid POLICY_DOCUMENT request returns expected response fields."""
        svc, cr, _, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        result = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, VALID_PDF_BODY)

        assert result["evidenceType"] == "POLICY_DOCUMENT"
        assert result["contentType"] == "application/pdf"
        assert result["status"] == "UPLOAD_PENDING"

    def test_evidence_saved_as_upload_pending(self) -> None:
        """Evidence record is persisted with UPLOAD_PENDING status."""
        svc, cr, er, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        result = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, VALID_VIDEO_BODY)

        saved = er.get(result["evidenceId"])
        assert saved is not None
        assert saved["status"] == "UPLOAD_PENDING"

    def test_storage_key_generated_by_backend(self) -> None:
        """storageKey is generated by the service, not taken from the body."""
        svc, cr, er, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        body_with_key = {**VALID_VIDEO_BODY, "storageKey": "client/supplied/key"}
        result = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, body_with_key)

        assert result["storageKey"] != "client/supplied/key"
        assert result["storageKey"].startswith("claims/")
        assert result["storageKey"].endswith("/object")

    def test_original_filename_not_in_storage_key(self) -> None:
        """The original filename must not appear anywhere in the storage key."""
        svc, cr, _, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        body = {**VALID_VIDEO_BODY, "fileName": "accident-video.mp4"}
        result = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, body)

        assert "accident-video.mp4" not in result["storageKey"]
        assert "accident" not in result["storageKey"]

    def test_path_traversal_filename_does_not_affect_storage_key(self) -> None:
        """Path-traversal filename cannot influence the storage key."""
        svc, cr, _, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        body = {**VALID_PDF_BODY, "fileName": "../../etc/passwd"}
        result = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, body)

        assert result["storageKey"].startswith("claims/")
        assert result["storageKey"].endswith("/object")
        assert "etc" not in result["storageKey"]
        assert "passwd" not in result["storageKey"]

    def test_presigned_url_uses_generated_storage_key(self) -> None:
        """The presigned URL generation is called with the backend storage key."""
        svc, cr, _, s3 = _make_evidence_service()
        cr.seed(_make_claim_item())

        result = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, VALID_VIDEO_BODY)

        assert len(s3.presigned_url_calls) == 1
        assert s3.presigned_url_calls[0]["key"] == result["storageKey"]
        assert s3.presigned_url_calls[0]["content_type"] == "video/mp4"

    def test_multiple_evidence_records_same_type_supported(self) -> None:
        """Multiple upload URL requests for the same type on same claim are all accepted."""
        svc, cr, er, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        r1 = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, VALID_VIDEO_BODY)
        r2 = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, VALID_VIDEO_BODY)

        assert r1["evidenceId"] != r2["evidenceId"]
        assert r1["storageKey"] != r2["storageKey"]
        assert len(er.list_by_claim(CLAIM_ID)) == 2

    def test_claim_not_found_raises_not_found_error(self) -> None:
        """Non-existent claimId raises NotFoundError (CLAIM_NOT_FOUND)."""
        svc, _, _, _ = _make_evidence_service()

        with pytest.raises(NotFoundError) as exc_info:
            svc.request_upload_url("CLM-missing", CLAIMANT_ID, VALID_VIDEO_BODY)
        assert exc_info.value.error_code == "CLAIM_NOT_FOUND"

    def test_unauthorized_claimant_raises_forbidden_error(self) -> None:
        """Claim owned by another claimant raises ForbiddenError."""
        svc, cr, _, _ = _make_evidence_service()
        cr.seed(_make_claim_item(claimant_id=OTHER_CLAIMANT_ID))

        with pytest.raises(ForbiddenError):
            svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, VALID_VIDEO_BODY)

    def test_invalid_mime_type_raises_validation_error(self) -> None:
        """Unsupported contentType raises ValidationError (UNSUPPORTED_CONTENT_TYPE)."""
        svc, cr, _, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        body = {**VALID_VIDEO_BODY, "contentType": "application/pdf"}
        with pytest.raises(ValidationError) as exc_info:
            svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, body)
        assert exc_info.value.error_code == "UNSUPPORTED_CONTENT_TYPE"

    def test_invalid_evidence_type_raises_validation_error(self) -> None:
        """Unknown evidenceType raises ValidationError (UNSUPPORTED_EVIDENCE_TYPE)."""
        svc, cr, _, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        body = {**VALID_VIDEO_BODY, "evidenceType": "DASHCAM"}
        with pytest.raises(ValidationError) as exc_info:
            svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, body)
        assert exc_info.value.error_code == "UNSUPPORTED_EVIDENCE_TYPE"

    def test_file_size_over_limit_raises_validation_error(self) -> None:
        """File size exceeding the configured limit raises FILE_SIZE_EXCEEDED."""
        svc, cr, _, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        body = {**VALID_VIDEO_BODY, "fileSizeBytes": 999_999_999}
        with pytest.raises(ValidationError) as exc_info:
            svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, body)
        assert exc_info.value.error_code == "FILE_SIZE_EXCEEDED"

    def test_response_contains_required_fields(self) -> None:
        """Response dict contains all fields required by the API contract."""
        svc, cr, _, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        result = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, VALID_VIDEO_BODY)

        for key in (
            "evidenceId",
            "claimId",
            "presignedUrl",
            "urlExpiresAt",
            "storageKey",
            "status",
            "evidenceType",
            "originalFileName",
            "contentType",
            "fileSizeBytes",
            "createdAt",
        ):
            assert key in result, f"Missing key in response: {key}"

    def test_original_file_name_preserved_in_response(self) -> None:
        """originalFileName is preserved as metadata in the response."""
        svc, cr, _, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        result = svc.request_upload_url(CLAIM_ID, CLAIMANT_ID, VALID_VIDEO_BODY)

        assert result["originalFileName"] == "accident.mp4"


# ── confirm_upload ────────────────────────────────────────────────────────────


class TestConfirmUpload:
    def _seed_pending_evidence(
        self,
        er: FakeEvidenceRepository,
        cr: FakeClaimRepository,
        evidence_id: str = EVIDENCE_ID,
        claim_id: str = CLAIM_ID,
    ) -> dict[str, Any]:
        """Seed both claim and evidence records for confirm tests."""
        claim_item = _make_claim_item(claim_id=claim_id)
        cr.seed(claim_item)
        ev_item = _make_evidence_item(evidence_id=evidence_id, claim_id=claim_id)
        er.seed(ev_item)
        return ev_item

    def test_successful_confirmation(self) -> None:
        """Happy path — evidence transitions to UPLOAD_COMPLETE."""
        svc, cr, er, _ = _make_evidence_service(object_exists=True)
        self._seed_pending_evidence(er, cr)

        result = svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)

        assert result["status"] == "UPLOAD_COMPLETE"
        assert "uploadedAt" in result

    def test_evidence_transition_persisted(self) -> None:
        """After confirmation, the persisted evidence record is UPLOAD_COMPLETE."""
        svc, cr, er, _ = _make_evidence_service(object_exists=True)
        self._seed_pending_evidence(er, cr)

        svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)

        saved = er.get(EVIDENCE_ID)
        assert saved is not None
        assert saved["status"] == "UPLOAD_COMPLETE"
        assert "uploadedAt" in saved

    def test_s3_object_missing_raises_validation_error(self) -> None:
        """If S3 object does not exist, ValidationError is raised."""
        svc, cr, er, _ = _make_evidence_service(object_exists=False)
        self._seed_pending_evidence(er, cr)

        with pytest.raises(ValidationError) as exc_info:
            svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)
        assert exc_info.value.error_code == "VALIDATION_ERROR"

    def test_evidence_already_complete_is_idempotent(self) -> None:
        """Confirming already-complete evidence returns the existing state."""
        svc, cr, er, _ = _make_evidence_service(object_exists=True)
        cr.seed(_make_claim_item())
        ev = _make_evidence_item(evidence_id=EVIDENCE_ID, status="UPLOAD_COMPLETE")
        ev["uploadedAt"] = FIXED_TIME
        er.seed(ev)

        result = svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)

        assert result["status"] == "UPLOAD_COMPLETE"
        # Conditional update not called (already complete) — evidence unchanged
        saved = er.get(EVIDENCE_ID)
        assert saved is not None
        assert saved["status"] == "UPLOAD_COMPLETE"

    def test_repeated_confirmation_is_safe(self) -> None:
        """Calling confirm_upload twice does not corrupt the record."""
        svc, cr, er, _ = _make_evidence_service(object_exists=True)
        self._seed_pending_evidence(er, cr)

        r1 = svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)
        r2 = svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)

        assert r1["status"] == "UPLOAD_COMPLETE"
        assert r2["status"] == "UPLOAD_COMPLETE"

    def test_claim_ownership_failure_raises_forbidden(self) -> None:
        """Claim belonging to another claimant raises ForbiddenError."""
        svc, cr, er, _ = _make_evidence_service()
        cr.seed(_make_claim_item(claimant_id=OTHER_CLAIMANT_ID))
        er.seed(_make_evidence_item())

        with pytest.raises(ForbiddenError):
            svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)

    def test_evidence_ownership_failure_raises_forbidden(self) -> None:
        """Evidence belonging to another claimant raises ForbiddenError."""
        svc, cr, er, _ = _make_evidence_service(object_exists=True)
        cr.seed(_make_claim_item())
        ev = _make_evidence_item(evidence_id=EVIDENCE_ID, claim_id=CLAIM_ID)
        ev["claimantId"] = OTHER_CLAIMANT_ID
        er.seed(ev)

        with pytest.raises(ForbiddenError):
            svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)

    def test_evidence_not_found_raises_not_found_error(self) -> None:
        """Non-existent evidenceId raises NotFoundError (EVIDENCE_NOT_FOUND)."""
        svc, cr, er, _ = _make_evidence_service()
        cr.seed(_make_claim_item())

        with pytest.raises(NotFoundError) as exc_info:
            svc.confirm_upload(CLAIM_ID, "EVD-missing", CLAIMANT_ID)
        assert exc_info.value.error_code == "EVIDENCE_NOT_FOUND"

    def test_evidence_belonging_to_different_claim_raises_not_found(self) -> None:
        """Evidence with a different claimId raises NotFoundError."""
        svc, cr, er, _ = _make_evidence_service(object_exists=True)
        cr.seed(_make_claim_item())
        ev = _make_evidence_item(evidence_id=EVIDENCE_ID, claim_id="CLM-different")
        er.seed(ev)

        with pytest.raises(NotFoundError) as exc_info:
            svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)
        assert exc_info.value.error_code == "EVIDENCE_NOT_FOUND"

    def test_claim_transitions_to_evidence_submitted(self) -> None:
        """After confirmation, claim status transitions to EVIDENCE_SUBMITTED."""
        svc, cr, er, _ = _make_evidence_service(object_exists=True)
        self._seed_pending_evidence(er, cr)

        svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)

        claim = cr.get(CLAIM_ID)
        assert claim is not None
        assert claim["status"] == "EVIDENCE_SUBMITTED"

    def test_claim_stays_evidence_submitted_on_second_confirm(self) -> None:
        """Second confirmation does not corrupt claim status."""
        svc, cr, er, _ = _make_evidence_service(object_exists=True)
        self._seed_pending_evidence(er, cr)

        svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)
        svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)

        claim = cr.get(CLAIM_ID)
        assert claim is not None
        assert claim["status"] == "EVIDENCE_SUBMITTED"

    def test_concurrent_confirmation_conditional_update_returns_false(self) -> None:
        """When conditional evidence update returns False, service handles it gracefully."""
        svc, cr, er, s3 = _make_evidence_service(object_exists=True)
        self._seed_pending_evidence(er, cr)

        # Pre-transition evidence to UPLOAD_COMPLETE to simulate a concurrent request
        er_item = er.get(EVIDENCE_ID)
        assert er_item is not None
        er_item["status"] = "UPLOAD_COMPLETE"
        er_item["uploadedAt"] = FIXED_TIME

        # Our request still proceeds without error — idempotent result
        result = svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)
        assert result["status"] == "UPLOAD_COMPLETE"

    def test_no_ai_processing_invoked(self) -> None:
        """confirm_upload must not call any AI/ML service."""
        svc, cr, er, s3 = _make_evidence_service(object_exists=True)
        self._seed_pending_evidence(er, cr)

        # Replace s3_repo with a mock and verify only expected methods are called
        mock_s3 = MagicMock()
        mock_s3.object_exists.return_value = True
        mock_s3.generate_presigned_put_url.return_value = "https://s3.example.com/key"
        svc._s3_repo = mock_s3

        svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)

        # Only object_exists should be called — no AI/ML methods
        mock_s3.object_exists.assert_called_once()
        mock_s3.generate_presigned_put_url.assert_not_called()

    def test_claim_not_found_during_confirm_raises_not_found(self) -> None:
        """confirm_upload raises NotFoundError if claim doesn't exist."""
        svc, _, er, _ = _make_evidence_service()
        er.seed(_make_evidence_item())

        with pytest.raises(NotFoundError) as exc_info:
            svc.confirm_upload("CLM-missing", EVIDENCE_ID, CLAIMANT_ID)
        assert exc_info.value.error_code == "CLAIM_NOT_FOUND"

    def test_response_contains_required_evidence_fields(self) -> None:
        """Confirm response contains all required evidence fields."""
        svc, cr, er, _ = _make_evidence_service(object_exists=True)
        self._seed_pending_evidence(er, cr)

        result = svc.confirm_upload(CLAIM_ID, EVIDENCE_ID, CLAIMANT_ID)

        for key in (
            "evidenceId",
            "claimId",
            "evidenceType",
            "status",
            "storageKey",
            "createdAt",
            "uploadedAt",
        ):
            assert key in result, f"Missing key in confirm response: {key}"
