"""
Service — Claim.

Orchestrates claim creation and retrieval workflows.  Sits between API
handlers and the domain/infrastructure layers.

Dependency direction:
  API Handler → ClaimService → domain functions + repositories → DynamoDB

This module contains no HTTP-specific code, no boto3 calls, and no
DynamoDB AttributeValue structures.  All AWS interaction is delegated to the
repository classes injected at construction time.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Any

from app.domain.claims import (
    ClaimStatus,
    build_claim_record,
    should_transition_to_evidence_submitted,
    validate_claim_input,
)
from app.domain.exceptions import ForbiddenError, NotFoundError
from app.infrastructure.dynamodb import ClaimRepository, EvidenceRepository

logger = logging.getLogger(__name__)

_ClockFn = Callable[[], str]


def _utc_now() -> str:
    return datetime.now(UTC).isoformat()


# ── Response models ───────────────────────────────────────────────────────────
# Plain dicts are used as the response representation so the API layer can
# serialise them directly to JSON without coupling to domain dataclasses.
# Keys follow the camelCase convention defined in the API contract (design.md).

ClaimResponse = dict[str, Any]
EvidenceResponse = dict[str, Any]
ClaimWithEvidenceResponse = dict[str, Any]


def _claim_to_response(item: dict[str, Any]) -> ClaimResponse:
    """Convert a DynamoDB item dict to a camelCase API response dict.

    Excludes ``claimantId`` from the public response per the design — the
    claimantId is internal, used only for authorization checks.
    """
    response: ClaimResponse = {
        "claimId": item["claimId"],
        "policyNumber": item["policyNumber"],
        "incidentDateTime": item["incidentDateTime"],
        "incidentLocation": item["incidentLocation"],
        "status": item["status"],
        "createdAt": item["createdAt"],
        "updatedAt": item["updatedAt"],
    }
    if "description" in item:
        response["description"] = item["description"]
    return response


def _evidence_to_response(item: dict[str, Any]) -> EvidenceResponse:
    """Convert a DynamoDB evidence item dict to an API response dict.

    Excludes internal fields not required by the public API contract.
    """
    response: EvidenceResponse = {
        "evidenceId": item["evidenceId"],
        "claimId": item["claimId"],
        "evidenceType": item["evidenceType"],
        "originalFileName": item["originalFileName"],
        "contentType": item["contentType"],
        "fileSizeBytes": item["fileSizeBytes"],
        "storageKey": item["storageKey"],
        "status": item["status"],
        "createdAt": item["createdAt"],
    }
    if "uploadedAt" in item:
        response["uploadedAt"] = item["uploadedAt"]
    return response


# ── ClaimService ──────────────────────────────────────────────────────────────


class ClaimService:
    """Application service for claim creation and retrieval.

    Parameters
    ----------
    claim_repo:
        Repository for claim persistence operations.
    evidence_repo:
        Repository for evidence persistence operations (needed for retrieval
        of associated evidence when fetching a claim).
    clock:
        Injectable time function — defaults to UTC now.  Pass a fixed-time
        lambda in tests for deterministic timestamps.
    """

    def __init__(
        self,
        claim_repo: ClaimRepository,
        evidence_repo: EvidenceRepository,
        clock: _ClockFn = _utc_now,
    ) -> None:
        self._claim_repo = claim_repo
        self._evidence_repo = evidence_repo
        self._clock = clock

    # ── Create claim ──────────────────────────────────────────────────────────

    def create_claim(
        self,
        claimant_id: str,
        body: dict[str, Any],
    ) -> ClaimResponse:
        """Create a new claim and persist it.

        The ``claimantId`` is sourced exclusively from the authenticated
        Cognito identity supplied by the API handler — it is never read from
        ``body``.  The ``claimId``, ``status``, ``createdAt``, and
        ``updatedAt`` are all generated by the domain layer.

        Parameters
        ----------
        claimant_id:
            Cognito ``sub`` of the authenticated user.
        body:
            Parsed request body containing ``policyNumber``,
            ``incidentDateTime``, ``incidentLocation``, and optionally
            ``description``.

        Returns
        -------
        ClaimResponse
            camelCase dict suitable for JSON serialisation.

        Raises
        ------
        ValidationError
            If any required field is missing or blank.
        """
        # Step 1: validate input (raises ValidationError on bad data)
        validate_claim_input(body)

        # Step 2: build the domain object (generates claimId, timestamps, status)
        claim = build_claim_record(
            claimant_id=claimant_id,
            policy_number=str(body["policyNumber"]),
            incident_date_time=str(body["incidentDateTime"]),
            incident_location=str(body["incidentLocation"]),
            description=str(body["description"]) if body.get("description") else None,
            clock=self._clock,
        )

        # Step 3: persist
        self._claim_repo.save(claim.to_dict())
        logger.info("Created claim claimId=%s", claim.claim_id)

        return _claim_to_response(claim.to_dict())

    # ── Get claim with evidence ────────────────────────────────────────────────

    def get_claim_with_evidence(
        self,
        claim_id: str,
        claimant_id: str,
    ) -> ClaimWithEvidenceResponse:
        """Retrieve a claim and all associated evidence records.

        Enforces that the authenticated claimant owns the claim.

        Parameters
        ----------
        claim_id:
            The ``CLM-<UUID>`` identifier from the request path.
        claimant_id:
            Cognito ``sub`` of the authenticated user.

        Returns
        -------
        ClaimWithEvidenceResponse
            camelCase dict with the claim fields and an ``evidence`` list.

        Raises
        ------
        NotFoundError
            If the claim does not exist (``CLAIM_NOT_FOUND``).
        ForbiddenError
            If the claim belongs to a different claimant.
        """
        # Step 1: fetch from persistence
        item = self._claim_repo.get(claim_id)
        if item is None:
            raise NotFoundError(
                f"Claim '{claim_id}' not found.",
                error_code="CLAIM_NOT_FOUND",
            )

        # Step 2: authorization check — must happen before returning any data
        if item.get("claimantId") != claimant_id:
            raise ForbiddenError(
                "You do not have permission to access this claim.",
            )

        # Step 3: fetch associated evidence via claimId-index GSI
        evidence_items = self._evidence_repo.list_by_claim(claim_id)

        # Step 4: build response
        response = _claim_to_response(item)
        response["evidence"] = [_evidence_to_response(ev) for ev in evidence_items]
        return response

    # ── Internal helper used by EvidenceService ───────────────────────────────

    def _get_owned_claim(
        self,
        claim_id: str,
        claimant_id: str,
    ) -> dict[str, Any]:
        """Fetch a claim and verify ownership.  Returns the raw DynamoDB item.

        Raises ``NotFoundError`` (CLAIM_NOT_FOUND) or ``ForbiddenError``
        before returning.  Internal method used by services that need to
        validate claim ownership without building the full evidence response.
        """
        item = self._claim_repo.get(claim_id)
        if item is None:
            raise NotFoundError(
                f"Claim '{claim_id}' not found.",
                error_code="CLAIM_NOT_FOUND",
            )
        if item.get("claimantId") != claimant_id:
            raise ForbiddenError(
                "You do not have permission to access this claim.",
            )
        return item

    def _try_transition_claim_to_evidence_submitted(
        self,
        claim_id: str,
        current_status: str,
    ) -> None:
        """Conditionally transition a claim to EVIDENCE_SUBMITTED if eligible.

        Uses a conditional DynamoDB update so concurrent confirmations are
        safe — only one will successfully apply the transition.  A failed
        condition (already transitioned) is silently ignored.

        Parameters
        ----------
        claim_id:
            The claim to potentially transition.
        current_status:
            The status value read from the claim item before evidence was
            confirmed.
        """
        completed_count = self._evidence_repo.count_completed_by_claim(claim_id)
        if should_transition_to_evidence_submitted(current_status, completed_count):
            self._claim_repo.update_status_conditional(
                claim_id=claim_id,
                expected_current_status=ClaimStatus.CREATED,
                new_status=ClaimStatus.EVIDENCE_SUBMITTED,
                updated_at=self._clock(),
            )
            logger.info("Transitioned claim claimId=%s CREATED -> EVIDENCE_SUBMITTED", claim_id)
